# This file was generated by GoReleaser. DO NOT EDIT.
cask "stave" do
  name "stave"
  desc "Configuration safety evaluation CLI"
  homepage "https://github.com/sufield/stave"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stave"

  on_macos do
    on_intel do
      url "https://github.com/sufield/stave/releases/download/v#{version}/stave_v#{version}_darwin_amd64.tar.gz"
      sha256 "b0f42e3134c1470e2389472a6416a34ad88c875b59989f1f9d7d4ded78fca822"
    end
    on_arm do
      url "https://github.com/sufield/stave/releases/download/v#{version}/stave_v#{version}_darwin_arm64.tar.gz"
      sha256 "21e6b25faffcc9818e3510e058ca171232f05f678e4ad1bc5e3690b319a59eaa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sufield/stave/releases/download/v#{version}/stave_v#{version}_linux_amd64.tar.gz"
      sha256 "b03cdc12573e636cbb5fade99120ddc6d76ac22da4a4faf1bf59a70de186df71"
    end
    on_arm do
      url "https://github.com/sufield/stave/releases/download/v#{version}/stave_v#{version}_linux_arm64.tar.gz"
      sha256 "1b9a4a641956f49fd081c734bcf733d02e9b25564189a76bbfa887c3c70c531a"
    end
  end

  # No zap stanza required
end
