# This file was generated by GoReleaser. DO NOT EDIT.
cask "stave" do
  name "stave"
  desc "Configuration safety evaluation CLI"
  homepage "https://github.com/sufield/stave"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stave"

  on_macos do
    on_intel do
      url "https://github.com/sufield/stave/releases/download/v#{version}/stave_v#{version}_darwin_amd64.tar.gz"
      sha256 "134c09f53fd3cc03c935ade85823e8cd0adde0b4b26e80dde59d266ddfd0d3a7"
    end
    on_arm do
      url "https://github.com/sufield/stave/releases/download/v#{version}/stave_v#{version}_darwin_arm64.tar.gz"
      sha256 "d46a8e1e277404c53999cda81eb4a0d58aced570861bb892b3e3d6450cf176eb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sufield/stave/releases/download/v#{version}/stave_v#{version}_linux_amd64.tar.gz"
      sha256 "c8e69478e9b2a080ff1e57932e27a8de383470c80d7aac427c1e4431edc959f5"
    end
    on_arm do
      url "https://github.com/sufield/stave/releases/download/v#{version}/stave_v#{version}_linux_arm64.tar.gz"
      sha256 "300921fbe39acf79cbc92d2a35a8ac4f5c8a9acae8c31bf6242ace36d609c3e4"
    end
  end

  # No zap stanza required
end
