# This file was generated by GoReleaser. DO NOT EDIT.
cask "stave" do
  name "stave"
  desc "Configuration safety evaluation CLI"
  homepage "https://github.com/sufield/stave"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stave"

  on_macos do
    on_intel do
      url "https://github.com/sufield/stave/releases/download/v#{version}/stave_v#{version}_darwin_amd64.tar.gz"
      sha256 "374c03ac4e9d5f9203c85afbeb107d032bddc25d46735d255592d567f0fc5646"
    end
    on_arm do
      url "https://github.com/sufield/stave/releases/download/v#{version}/stave_v#{version}_darwin_arm64.tar.gz"
      sha256 "a17b75aecad762262d5a068b296fcd1824007105b92c58bf9fee0de4e5a1fc83"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sufield/stave/releases/download/v#{version}/stave_v#{version}_linux_amd64.tar.gz"
      sha256 "075f19a77bb2b0227de2a6ee1859baa9266e56ca30c00efa8acda4ac57f92259"
    end
    on_arm do
      url "https://github.com/sufield/stave/releases/download/v#{version}/stave_v#{version}_linux_arm64.tar.gz"
      sha256 "b32a43e8c72eec5b1306f6f1411bb85a926212ab1097481d326e97bb116cd1e9"
    end
  end

  # No zap stanza required
end
